const mathjaxConfig = {
  tex: {
    macros: {
      enc: ["\\left( #1 \\right)", 1],
      encsq: ["\\left[ #1 \\right] ", 1],
      encbr: ["\\left\\lbrace #1 \\right\\rbrace ", 1],
      mean: ["\\left\\langle #1 \\right\\rangle", 1],
      efrac: ["\\enc{\\frac{#1}{#2}}", 2],
      cross: "\\times",
      diff: [" \\frac{d #1}{d #2} ", 2],
      pd: ["\\frac{\\partial #1}{\\partial #2}", 2],
      pdd: ["\\frac{\\partial^2 #1}{\\partial #2^2}", 2],
      pdc: [" \\left( \\frac{\\partial #1}{\\partial #2} \\right)_{#3}", 3],
      dive: "\\vec{\\nabla}\\cdot",
      grad: "\\vec{\\nabla}",
      curl: " \\nabla \\times",
      lap: "\\nabla^2 ",
      com: ["\\left[ \\, #1 \\, , \\, #2 \\right]", 2],
      anticom: ["\\left\\lbrace \\, #1 \\, , \\, #2 \\right\\rbrace", 2],
      bra: ["\\left\\langle #1 \\right\\rvert", 1],
      ket: ["\\left| #1 \\right\\rangle ", 1],
      braket: [
        "\\left< #1 \\vphantom{#2} \\right| \\left. #2 \\vphantom{#1} \\right>",
        2,
      ],
      Obraket: [
        " \\left< #1 \\vphantom{#2} \\vphantom{#3} \\right| #2 \\left| \\vphantom{#1} \\vphantom{#2} #3 \\right>",
        3,
      ],
      con: ["\\left< #1 \\,,\\, #2 \\right>", 2],
      abs: ["\\left\\lvert #1 \\right\\rvert", 1],
      set: ["\\left\\lbrace #1 \\right\\rbrace", 1],
      cond: ["\\left. \\left( #1 \\right) \\right|_{#2} ", 2],
      Real: ["\\mathbb{Re}\\encsq{#1}", 1],
      sinc: "\\mathrm{sinc}",
      atan: "{\\tan}^{-1}",
      asin: "{\\sin}^{-1}",
      acos: "{\\cos}^{-1}",
      ODR: ["\\times 10^{#1}", 1],
      de: "^\\circ",
      ten: ["\\times \\mathrm{10}^\\mathrm{#1}", 1],
      unit: ["\\mathrm{\\,#1}", 1],
      mum: "\\,\\mu\\mathrm{m}",
      micron: "\\,\\mu\\mathrm{m}",
      cm: "\\,\\mathrm{cm}",
      mm: "\\,\\mathrm{mm}",
      mus: "\\,\\mu\\mathrm{s}",
      keV: "\\,\\mathrm{ke\\hspace{-.08em}V}",
      MeV: "\\,\\mathrm{Me\\hspace{-.08em}V}",
      MeVns: "\\mathrm{Me\\hspace{-.08em}V}",
      GeV: "\\,\\mathrm{Ge\\hspace{-.08em}V}",
      GeVns: "\\mathrm{Ge\\hspace{-.08em}V}",
      gev: "\\GeV",
      TeV: "\\,\\mathrm{Te\\hspace{-.08em}V}",
      TeVns: "\\mathrm{Te\\hspace{-.08em}V}",
      PeV: "\\,\\mathrm{Pe\\hspace{-.08em}V}",
      keVc: "{\\,\\mathrm{ke\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c}",
      MeVc: "{\\,\\mathrm{Me\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c}",
      GeVc: "{\\,\\mathrm{Ge\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c}",
      GeVcns:
        "{\\mathrm{Ge\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c}",
      TeVc: "{\\,\\mathrm{Te\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c}",
      keVcc:
        "{\\,\\mathrm{ke\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c^\\mathrm{2}}",
      MeVcc:
        "{\\,\\mathrm{Me\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c^\\mathrm{2}}",
      GeVcc:
        "{\\,\\mathrm{Ge\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c^\\mathrm{2}}",
      GeVccns:
        "{\\mathrm{Ge\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c^\\mathrm{2}}",
      TeVcc:
        "{\\,\\mathrm{Te\\hspace{-.08em}V\\hspace{-0.16em}/\\hspace{-0.08em}}c^\\mathrm{2}}",
      percms: "\\,\\mathrm{cm}^\\mathrm{$-$2}\\,\\mathrm{s}^\\mathrm{$-$1}",
      lumi: "\\mathcal{L}",
      Lumi: "\\mathcal{L}",
      lowlumi:
        "\\mathcal{L}=\\mathrm{2}\\times \\mathrm{10}^\\mathrm{33}\\,\\mathrm{cm}^\\mathrm{$-$2}\\,\\mathrm{s}^\\mathrm{$-$1}",
      PT: "p_{\\mathrm{T}}",
      pt: "p_{\\mathrm{T}}",
      ET: "E_{\\mathrm{T}}",
      HT: "H_{\\mathrm{T}}",
      et: "E_{\\mathrm{T}}",
      Em: "E\\hspace{-0.6em}/",
      Pm: "p\\hspace{-0.5em}/",
      PTm: "{p}_\\mathrm{T}\\hspace{-1.02em}/\\kern 0.5em",
      PTslash: "\\PTm",
      ETm: "E_{\\mathrm{T}}^{\\mathrm{miss}}",
      MET: "\\ETm",
      ETmiss: "\\ETm",
      ETslash: "E_{\\mathrm{T}}\\hspace{-1.1em}/\\kern0.45em",
      VEtmiss: "{\\vec E}_{\\mathrm{T}}^{\\mathrm{miss}}",
      ptvec: "{\\vec p}_{\\mathrm{T}}",
      ptvecmiss: "{\\vec p}_{\\mathrm{T}}^{\\kern1pt\\mathrm{miss}}",
      cmsSymbolFace: "\\mathrm",
      dd: ["\\frac{\\cmsSymbolFace{d} #1}{\\cmsSymbolFace{d} #2}", 2],
      ddinline: ["\\cmsSymbolFace{d} #1/\\cmsSymbolFace{d} #2", 2],
      rd: "\\cmsSymbolFace{d}",
      re: "\\cmsSymbolFace{e}",
      zp: "\\cmsSymbolFace{Z}^\\prime",
      JPsi: "\\cmsSymbolFace{J}\\hspace{-.08em}/\\hspace{-.14em}\\psi",
      Z: "\\cmsSymbolFace{Z}",
      ttbar: "\\cmsSymbolFace{t}\\overline{\\cmsSymbolFace{t}}",
      cPgn: "\\nu",
      cPagn: "\\overline{\\nu}",
      cPgg: "\\gamma",
      cPJgy: "\\cmsSymbolFace{J}\\hspace{-.08em}/\\hspace{-.14em}\\psi",
      cPZ: "\\cmsSymbolFace{Z}",
      cPZpr: "\\cmsSymbolFace{Z}^\\prime",
      cPqt: "\\cmsSymbolFace{t}",
      cPqb: "\\cmsSymbolFace{b}",
      cPqc: "\\cmsSymbolFace{c}",
      cPqs: "\\cmsSymbolFace{s}",
      cPqu: "\\cmsSymbolFace{u}",
      cPqd: "\\cmsSymbolFace{d}",
      cPq: "\\cmsSymbolFace{q}",
      cPg: "\\cmsSymbolFace{g}",
      cPG: "\\cmsSymbolFace{G}",
      cPaqt: "\\overline{\\cmsSymbolFace{t}}",
      cPaqb: "\\overline{\\cmsSymbolFace{b}}",
      cPaqc: "\\overline{\\cmsSymbolFace{c}}",
      cPaqs: "\\overline{\\cmsSymbolFace{s}}",
      cPaqu: "\\overline{\\cmsSymbolFace{u}}",
      cPaqd: "\\overline{\\cmsSymbolFace{d}}",
      cPaq: "\\overline{\\cmsSymbolFace{q}}",
      cPKstz: "\\cmsSymbolFace{K}^{\\ast0}",
      AFB: "A_\\mathrm{FB}",
      wangle: "\\sin^{2}\\theta_{\\mathrm{eff}}^\\mathrm{lept}(M^2_{\\Z})",
      stat: "\\,\\mathrm{(stat)}",
      syst: "\\,\\mathrm{(syst)}",
      thy: "\\,\\mathrm{(theo)}",
      lum: "\\,\\mathrm{(lumi)}",
      kt: "k_{\\mathrm{T}}",
      BC: "\\cmsSymbolFace{B_{c}}",
      bbarc: "\\PQb\\PAQc",
      bbbar: "\\PQb\\PAQb",
      ccbar: "\\PQc\\PAQc",
      qqbar: "\\PQq\\PAQq",
      bspsiphi: "\\cmsSymbolFace{B_s} \\to \\JPsi\\, \\phi",
      EE: "\\Pep\\Pem",
      MM: "\\Pgmp\\Pgmm",
      TT: "\\Pgt^{+}\\Pgt^{-}",
      HGG: "\\cmsSymbolFace{H}\\to\\gamma\\gamma",
      GAMJET: "\\gamma + \\mathrm{jet}",
      PPTOJETS: "\\Pp\\Pp\\to\\mathrm{jets}",
      PPTOGG: "\\Pp\\Pp\\to\\gamma\\gamma",
      PPTOGAMJET: "\\Pp\\Pp\\to\\gamma + \\mathrm{jet}",
      MH: "M_{\\PH}",
      RNINE: "R_\\mathrm{9}",
      DR: "\\Delta R",
      ga: "\\gtrsim",
      la: "\\lesssim",
      swsq: "\\sin^2\\theta_\\cmsSymbolFace{W}",
      cwsq: "\\cos^2\\theta_\\cmsSymbolFace{W}",
      tanb: "\\tan\\beta",
      tanbsq: "\\tan^{2}\\beta",
      sidb: "\\sin 2\\beta",
      alpS: "\\alpha_S",
      alpt: "\\tilde{\\alpha}",
      QL: "\\cmsSymbolFace{Q}_\\cmsSymbolFace{L}",
      sQ: "\\widetilde{\\cmsSymbolFace{Q}}",
      sQL: "\\widetilde{\\cmsSymbolFace{Q}}_\\cmsSymbolFace{L}",
      ULC: "\\cmsSymbolFace{U}_\\cmsSymbolFace{L}^\\cmsSymbolFace{C}",
      sUC: "\\widetilde{\\cmsSymbolFace{U}}^\\cmsSymbolFace{C}",
      sULC: "\\widetilde{\\cmsSymbolFace{U}}_\\cmsSymbolFace{L}^\\cmsSymbolFace{C}",
      DLC: "\\cmsSymbolFace{D}_\\cmsSymbolFace{L}^\\cmsSymbolFace{C}",
      sDC: "\\widetilde{\\cmsSymbolFace{D}}^\\cmsSymbolFace{C}",
      sDLC: "\\widetilde{\\cmsSymbolFace{D}}_\\cmsSymbolFace{L}^\\cmsSymbolFace{C}",
      LL: "\\cmsSymbolFace{L}_\\cmsSymbolFace{L}",
      sL: "\\widetilde{\\cmsSymbolFace{L}}",
      sLL: "\\widetilde{\\cmsSymbolFace{L}}_\\cmsSymbolFace{L}",
      ELC: "\\cmsSymbolFace{E}_\\cmsSymbolFace{L}^\\cmsSymbolFace{C}",
      sEC: "\\widetilde{\\cmsSymbolFace{E}}^\\cmsSymbolFace{C}",
      sELC: "\\widetilde{\\cmsSymbolFace{E}}_\\cmsSymbolFace{L}^\\cmsSymbolFace{C}",
      sEL: "\\widetilde{\\cmsSymbolFace{E}}_\\cmsSymbolFace{L}",
      sER: "\\widetilde{\\cmsSymbolFace{E}}_\\cmsSymbolFace{R}",
      sFer: "\\widetilde{\\cmsSymbolFace{f}}",
      sQua: "\\widetilde{\\cmsSymbolFace{q}}",
      sUp: "\\widetilde{\\cmsSymbolFace{u}}",
      suL: "\\widetilde{\\cmsSymbolFace{u}}_\\cmsSymbolFace{L}",
      suR: "\\widetilde{\\cmsSymbolFace{u}}_\\cmsSymbolFace{R}",
      sDw: "\\widetilde{\\cmsSymbolFace{d}}",
      sdL: "\\widetilde{\\cmsSymbolFace{d}}_\\cmsSymbolFace{L}",
      sdR: "\\widetilde{\\cmsSymbolFace{d}}_\\cmsSymbolFace{R}",
      sTop: "\\widetilde{\\cmsSymbolFace{t}}",
      stL: "\\widetilde{\\cmsSymbolFace{t}}_\\cmsSymbolFace{L}",
      stR: "\\widetilde{\\cmsSymbolFace{t}}_\\cmsSymbolFace{R}",
      stone: "\\widetilde{\\cmsSymbolFace{t}}_1",
      sttwo: "\\widetilde{\\cmsSymbolFace{t}}_2",
      sBot: "\\widetilde{\\cmsSymbolFace{b}}",
      sbL: "\\widetilde{\\cmsSymbolFace{b}}_\\cmsSymbolFace{L}",
      sbR: "\\widetilde{\\cmsSymbolFace{b}}_\\cmsSymbolFace{R}",
      sbone: "\\widetilde{\\cmsSymbolFace{b}}_1",
      sbtwo: "\\widetilde{\\cmsSymbolFace{b}}_2",
      sLep: "\\widetilde{\\cmsSymbolFace{l}}",
      sLepC: "\\widetilde{\\cmsSymbolFace{l}}^\\cmsSymbolFace{C}",
      sEl: "\\widetilde{\\cmsSymbolFace{e}}",
      sElC: "\\widetilde{\\cmsSymbolFace{e}}^\\cmsSymbolFace{C}",
      seL: "\\widetilde{\\cmsSymbolFace{e}}_\\cmsSymbolFace{L}",
      seR: "\\widetilde{\\cmsSymbolFace{e}}_\\cmsSymbolFace{R}",
      snL: "\\widetilde{\\nu}_L",
      sMu: "\\widetilde{\\mu}",
      sNu: "\\widetilde{\\nu}",
      sTau: "\\widetilde{\\tau}",
      Glu: "\\cmsSymbolFace{g}",
      sGlu: "\\widetilde{\\cmsSymbolFace{g}}",
      Wpm: "\\cmsSymbolFace{W}^{\\pm}",
      sWpm: "\\widetilde{\\cmsSymbolFace{W}}^{\\pm}",
      Wz: "\\cmsSymbolFace{W}^{0}",
      sWz: "\\widetilde{\\cmsSymbolFace{W}}^{0}",
      sWino: "\\widetilde{\\cmsSymbolFace{W}}",
      Bz: "\\cmsSymbolFace{B}^{0}",
      sBz: "\\widetilde{\\cmsSymbolFace{B}}^{0}",
      sBino: "\\widetilde{\\cmsSymbolFace{B}}",
      Zz: "\\cmsSymbolFace{Z}^{0}",
      sZino: "\\widetilde{\\cmsSymbolFace{Z}}^{0}",
      sGam: "\\widetilde{\\gamma}",
      chiz: "\\widetilde{\\chi}^{0}",
      chip: "\\widetilde{\\chi}^{+}",
      chim: "\\widetilde{\\chi}^{-}",
      chipm: "\\widetilde{\\chi}^{\\pm}",
      Hone: "\\cmsSymbolFace{H}_\\cmsSymbolFace{d}",
      sHone: "\\widetilde{\\cmsSymbolFace{H}}_\\cmsSymbolFace{d}",
      Htwo: "\\cmsSymbolFace{H}_\\cmsSymbolFace{u}",
      sHtwo: "\\widetilde{\\cmsSymbolFace{H}}_\\cmsSymbolFace{u}",
      sHig: "\\widetilde{\\cmsSymbolFace{H}}",
      sHa: "\\widetilde{\\cmsSymbolFace{H}}_\\cmsSymbolFace{a}",
      sHb: "\\widetilde{\\cmsSymbolFace{H}}_\\cmsSymbolFace{b}",
      sHpm: "\\widetilde{\\cmsSymbolFace{H}}^{\\pm}",
      hz: "\\cmsSymbolFace{h}^{0}",
      Hz: "\\cmsSymbolFace{H}^{0}",
      Az: "\\cmsSymbolFace{A}^{0}",
      Hpm: "\\cmsSymbolFace{H}^{\\pm}",
      sGra: "\\widetilde{\\cmsSymbolFace{G}}",
      mtil: "\\widetilde{m}",
      rpv: "\\rlap{\\kern.2em/}R",
      LLE: "LL\\bar{E}",
      LQD: "LQ\\bar{D}",
      UDD: "\\overline{UDD}",
      Lam: "\\lambda",
      spinbd: ["\\bar{#1}_{\\dot{#2}}", 2],
      MD: "{M_\\mathrm{D}}",
      Lamp: "\\lambda'",
      Lampp: "\\lambda''",
      Pgn: "\\nu",
      Pagn: "\\overline{\\nu}",
      PH: "\\cmsSymbolFace{H}",
      Ph: "\\cmsSymbolFace{h}",
      Pa: "\\cmsSymbolFace{a}",
      PSA: "\\cmsSymbolFace{A}",
      PJGy: "\\cmsSymbolFace{J}\\hspace{-.08em}/\\hspace{-.14em}\\psi",
      PBzs: "\\cmsSymbolFace{B}^0_\\cmsSymbolFace{s}",
      Pg: "\\cmsSymbolFace{g}",
      PSg: "\\widetilde{\\cmsSymbolFace{g}}",
      PSQ: "\\widetilde{\\cmsSymbolFace{q}}",
      PSGm: "\\widetilde{\\mu}",
      PSe: "\\widetilde{\\cmsSymbolFace{e}}",
      PASQ: "\\overline{\\widetilde{\\cmsSymbolFace{q}}}",
      PXXG: "\\cmsSymbolFace{G}",
      PXXSG: "\\widetilde{\\PXXG}",
      PSGcp: "\\widetilde{\\chi}^+",
      PSGc: "\\widetilde{\\chi}",
      PSGcz: "\\widetilde{\\chi}^0",
      PSGczDo: "\\widetilde{\\chi}^{0}_{1}",
      PSGcmDo: "\\widetilde{\\chi}^{-}_{1}",
      PSGczDt: "\\widetilde{\\chi}^{0}_{2}",
      PSGcpm: "\\widetilde{\\chi}^\\pm",
      PSGcpmDo: "\\widetilde{\\chi}^\\pm_{1}",
      PSGcpDo: "\\widetilde{\\chi}^{+}_{1}",
      Pl: "\\cmsSymbolFace{l}",
      PAl: "\\overline{\\cmsSymbolFace{l}}",
      PGnl: "\\nu_\\cmsSymbolFace{l}",
      PAGnl: "\\overline{\\nu}_\\cmsSymbolFace{l}",
      PQtpr: "\\cmsSymbolFace{t}^{\\prime}",
      PAQtpr: "\\bar{\\cmsSymbolFace{t}}^\\prime",
      PQbpr: "\\cmsSymbolFace{b}^{\\prime}",
      PAQbpr: "\\bar{\\cmsSymbolFace{b}}^\\prime",
      PGg: "\\gamma",
      PKzS: "\\cmsSymbolFace{K}^0_\\cmsSymbolFace{S}",
      PBs: "\\cmsSymbolFace{B}_\\cmsSymbolFace{s}",
      PSQu: "\\widetilde{\\cmsSymbolFace{u}}",
      PSQd: "\\widetilde{\\cmsSymbolFace{d}}",
      PSQc: "\\widetilde{\\cmsSymbolFace{c}}",
      PSQs: "\\widetilde{\\cmsSymbolFace{s}}",
      PSQt: "\\widetilde{\\cmsSymbolFace{t}}",
      PSQb: "\\widetilde{\\cmsSymbolFace{b}}",
      PASQt: "\\overline{\\widetilde{\\cmsSymbolFace{t}}}",
      PASQb: "\\overline{\\widetilde{\\cmsSymbolFace{b}}}",
      PSGt: "\\widetilde{\\tau}",
      PZ: "\\cmsSymbolFace{Z}",
      PZpr: "\\cmsSymbolFace{Z}^\\prime",
      PW: "\\cmsSymbolFace{W}\\xspace",
      PWpr: "\\cmsSymbolFace{W}^\\prime",
      PGn: "\\nu",
      PAGn: "\\overline{\\nu}",
      PSQtDo: "\\widetilde{\\cmsSymbolFace{t}}_1",
      PSQtDt: "\\widetilde{\\cmsSymbolFace{t}}_2",
      PQt: "\\cmsSymbolFace{t}",
      PAQt: "\\overline{\\cmsSymbolFace{t}}",
      PQb: "\\cmsSymbolFace{b}",
      PAQb: "\\overline{\\cmsSymbolFace{b}}",
      PGm: "\\mu",
      PGmm: "\\mu^-",
      PGmp: "\\mu^+",
      PGmpm: "\\mu^\\pm",
      PGt: "\\tau",
      PAGt: "\\overline{\\tau}",
      PQq: "\\cmsSymbolFace{q}",
      PQd: "\\cmsSymbolFace{d}",
      PQu: "\\cmsSymbolFace{u}",
      PQs: "\\cmsSymbolFace{s}",
      PQc: "\\cmsSymbolFace{c}",
      PAQq: "\\overline{\\cmsSymbolFace{q}}",
      PAQd: "\\overline{\\cmsSymbolFace{d}}",
      PAQu: "\\overline{\\cmsSymbolFace{u}}",
      PAQs: "\\overline{\\cmsSymbolFace{s}}",
      PAQc: "\\overline{\\cmsSymbolFace{c}}",
      PGne: "\\nu_\\cmsSymbolFace{e}",
      PAGne: "\\overline{\\nu}_\\cmsSymbolFace{e}",
      PGnGm: "\\nu_\\PGm",
      PAGnGm: "\\overline{\\nu}_\\PGm",
      PGnGt: "\\nu_\\PGt",
      PAGnGt: "\\overline{\\nu}_\\PGt",
      PAp: "\\overline{\\cmsSymbolFace{p}}",
      Pepm: "\\cmsSymbolFace{e}^\\pm",
      Mpl: "{M_\\mathrm{Pl}}",
      Rinv: "{R}^{-1}",
    },
  },
};

export default mathjaxConfig;
